version: '3.8'

services:
  db:
    image: mysql:8
    container_name: bot_ch_v.1.0.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "30370:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: